#if !canImport(ObjectiveC)
import XCTest

extension LilliputTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LilliputTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LilliputTests.__allTests__LilliputTests),
    ]
}
#endif
